#include "MotionMain.h";

enum 
{
    CMD_NULL = 0,
    CMD_COMMON_SYSTEM ,
	CMD_COMMON_PROPERTY_SET,
	CMD_COMMON_PROPERTY_GET,
	CMD_GROUP_SYSTEM,
	CMD_GROUP_STATE,
	CMD_GROUP_MOTION,
	CMD_AXIS_SYSTEM,
	CMD_AXIS_STATE,
	CMD_AXIS_MOTION_IO,
	CMD_AXIS_MOTION_JOG,
	CMD_AXIS_MOTION_P2P
};

void MotionDataRecord(COMMAND_NODE_Queue* QCOMMAND)
{
	switch (QCOMMAND->Dequene().cmd)
	{
	case CMD_NULL:
		break;
	case CMD_COMMON_PROPERTY_SET:

		break;
	}	
}

void MotionMain()
{
}